### ISSUE TITLE
关于获取position

### ISSUE THREAD

**Issue by 06304322** [smuyyh/EasyAdapter#5]
protected void onBindData(EasyRVHolder viewHolder, int position, MessageListInfo item) {}
为什么我获取不到当前item的position，都是获取的不正确的position。求解答？？

**Comment by smuyyh** [comment]
你是说onBindData的position参数不对？

**Comment by 06304322** [comment]
是的。显示的position都不是我当前选择的。

**Comment by smuyyh** [comment]
当前选择？这个就相当于走getView方法了  正常来说就是应该走到屏幕显示的最后一个

**Comment by 06304322** [comment]
那么请问怎么才能获得当前item的position呢？

**Comment by smuyyh** [comment]
我还是不明白当前item是指什么？   一个屏幕能显示好几个item，哪一个才是当前item...

**Comment by 06304322** [comment]
我说的就是列表项的position
       viewHolder.getItemView().setOnClickListener(new View.OnClickListener() {
            @Override
            public viod onClick(View view) {
                ToastUtil.showShort(context, position+ "");
            }
        });
我点击那个列表项position应该显示相应的position，可是它始终显示的是可见的最后一个，是混乱的

**Comment by smuyyh** [comment]
我的都不会啊。整段代码贴出来看看！下面这样子是可以的

``` java
@Override
    protected void onBindData(EasyRVHolder viewHolder, final int position, Bean item) {
        //如果不想暴露 item 的点击事件就直接继承 EasyRVAdapter 即可
        super.onBindData(viewHolder, position, item);//调用父类来暴露item的点击事件
        viewHolder.setText(R.id.tv, item.name);
        viewHolder.getItemView().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(mContext, position+"---", Toast.LENGTH_SHORT).show();
            }
        });
    }
```

**Comment by 06304322** [comment]
感谢你的解答，问题已经解决。
