### ISSUE TITLE
通过Adapter.setClick实现点击监听事件没有效果。

### ISSUE THREAD

**Issue by 06304322** [smuyyh/EasyAdapter#6]
trackListAdapter.setClick(new BaseRVAdapter.OnItemClick<Track.TrackContent>() {
            private boolean isLike = false;

            @Override
            public void onItemClick(View v, int vId, int position, Track.TrackContent item) {
                int num = item.totalLaud;
                TextView likeTv = (TextView) v.findViewById(R.id.track_person_list_item_like_tv);
                ImageView likeIv = (ImageView) v.findViewById(R.id.track_person_list_item_like_iv);
                switch (vId) {
                    case R.id.track_person_list_item_like_tv:
                        if (isLike) {
                            num--;
                            likeTv.setText(num + "");
                            likeIv.setImageResource(R.mipmap.like);
                            isLike = false;
                        } else {
                            num++;
                            likeTv.setText(num + "");
                            likeIv.setImageResource(R.mipmap.like_green);
                            isLike = true;
                        }
                        break;
                }
            }
        });

**Comment by smuyyh** [comment]
是不是没有取得焦点

**Comment by 06304322** [comment]
你的demo也不能实现监听，你写了那个监听但是没用。

**Comment by smuyyh** [comment]
这个上次是另一人提交了PR，我还没来得及测。  晚点有空试试

**Comment by smuyyh** [comment]
@06304322 初步看了一下，RecyclerView adapter的 setOnClick没生效，是因为在adapter的onBindData里面添加了点击事件了，覆盖掉setOnClick了，删掉就可以了。这个方法本身是没问题的~

**Comment by 06304322** [comment]
只能监听item吗？item里面的子控件还是不能实现监听。

**Comment by smuyyh** [comment]
子控件在onBindData直接监听  没问题吧？

**Comment by 06304322** [comment]
onBindData是可以监听的。我想实现一个点击点赞的效果，可是会出现数据混乱，你这边有什么解决方法吗？

**Comment by smuyyh** [comment]
数据混乱？乱序？

**Comment by 06304322** [comment]
对的，列表滚动后数据会改变。

**Comment by smuyyh** [comment]
这个主要是item复用的问题。正常对item里的控件监听的话都有可能发生这个问题~ 比如Edittext。

思路主要是通过setTag。这是edittext处理的代码，可以稍微参考一下。

```java
final EditText editText = viewHolder.getView(R.id.et_add_house_comment_has_choose_item_input);

            editText.setTag(item);

            editText.addTextChangedListener(new TextWatcher() {
                @Override
                public void beforeTextChanged(CharSequence s, int start, int count, int after) {

                }

                @Override
                public void onTextChanged(CharSequence s, int start, int before, int count) {
                    ItemData data = (ItemData) editText.getTag();
                    if (data != null) {
                        data.setInput(s + "");
                    }
                }

                @Override
                public void afterTextChanged(Editable s) {

                }
            });

            if (!TextUtils.isEmpty(item.getInput())) {
                editText.setText(item.getInput());
            } else {
                editText.setText("");
            }
```

**Comment by 06304322** [comment]
好的，谢谢。
